 /*const randomNumber=Math.random();
  var generatedSymbol; // stores the symbol generated by program
  let yourScore=0; // stores the user score
  let opponentScore=0; //stores opponent score
  let clickCounter=0; //counts the clicks
  

  //randomNumberGenerator function decides the symbol generated
  function randomNumberGenerator()
  {
    if(randomNumber>=0 && randomNumber< 1/3)
      {
        generatedSymbol="rock";
      }
  
    else if(randomNumber>=1/3 && randomNumber< 2/3)
        {
          generatedSymbol="paper";
        }
    else if(randomNumber>=2/3 && randomNumber< 1)
          {
           generatedSymbol="sissors";
          }
  
  }

//refree function used in assigning points
  function refree(userSymbol)
  { 
    randomNumberGenerator();
    
  if(userSymbol===generatedSymbol)
      {
          console.log("tie");
      }

  else if(userSymbol==="rock" && (generatedSymbol==="sissors"))
      {
          console.log(`you win with ${userSymbol} and ${generatedSymbol}`);
          yourScore+=1;
      }
  else if(userSymbol==="paper" && (generatedSymbol==="rock"))
      {
          console.log(`you win with ${userSymbol} and ${generatedSymbol}`);
          yourScore+=1;
      }
  else if(userSymbol==="sissors" && (generatedSymbol==="paper"))
      {
          console.log(`you win with ${userSymbol} and ${generatedSymbol}`);
           yourScore+=1;
      }

  else 
       {
        opponentScore+=1;
        console.log(`Computer wins this time ${userSymbol} and ${generatedSymbol}`);
        
      }
  
  document.getElementById('scoreDisplay').textContent = `Your Score: ${yourScore}\u00A0\u00A0\u00A0\u00A0Opponent Score: ${opponentScore}`;
  

  }

  function reset()
  {
    document.getElementById('scoreDisplay').textContent = `Your Score: ${yourScore=0}\u00A0\u00A0\u00A0\u00A0Opponent Score: ${opponentScore=0}`;
    
  }*/

   //stores opponent score
    let userSymbol;
    let generatedSymbol;
    
 
  const user={
    name:'user',
    score:0,
    round:0,
    numGenerator:function() 
      { const randomNumber=Math.random();
        if(randomNumber>=0 && randomNumber< 1/3)
          {  
            generatedSymbol="rock";}
      
        else if(randomNumber>=1/3 && randomNumber< 2/3)
            {
              generatedSymbol="paper";  }
        else if(randomNumber>=2/3 && randomNumber< 1)
              { 
                generatedSymbol="sissors"; }
      },


    result:function(userSymbol)
      
        { this.numGenerator();
         if(userSymbol===generatedSymbol)
            {
                console.log("tie");
                console.log(`you win with ${userSymbol} and ${generatedSymbol}`);
            }
      
        else if(userSymbol==="rock" && (generatedSymbol==="sissors"))
            {
                console.log(`you win with ${userSymbol} and ${generatedSymbol}`);
                this.score+=1;
            }
        else if(userSymbol==="paper" && (generatedSymbol==="rock"))
            {
                console.log(`you win with ${userSymbol} and ${generatedSymbol}`);
                this.score+=1;
            }
        else if(userSymbol==="sissors" && (generatedSymbol==="paper"))
            {
                console.log(`you win with ${userSymbol} and ${generatedSymbol}`);
                this.score+=1;
            }
      
        else 
             {
              this.opponentScore+=1;
              console.log(`Computer wins this time ${userSymbol} and ${generatedSymbol}`);
              
            }
            document.getElementById('scoreDisplay').textContent = `Your Score: ${this.score}\u00A0\u00A0\u00A0\u00A0Opponent Score: ${this.opponentScore}`;

      },
      resetScore:function reset()
      {
        document.getElementById('scoreDisplay').textContent = `Your Score: ${this.score=0}\u00A0\u00A0\u00A0\u00A0Opponent Score: ${this.opponentScore=0}`;
    
    },
    opponentScore:0

  };

  